
    create table abbonamento_attivita (
        abbonamento_id integer not null,
        attivita_id integer not null
    );

    create table abbonamento_socio (
        data_iscrizione date not null,
        id integer generated by default as identity,
        id_socio integer,
        primary key (id)
    );

    create table attivita (
        id integer generated by default as identity,
        descrizione varchar(100) not null unique,
        primary key (id)
    );

    create table certificato_medico (
        data_certificato date,
        id integer generated by default as identity,
        socio_id integer unique,
        tipo_certificato boolean,
        primary key (id)
    );

    create table messaggi_systema (
        lang varchar(4) not null,
        code varchar(20) not null,
        messaggio varchar(255),
        primary key (lang, code)
    );

    create table socio_palestra (
        id integer generated by default as identity,
        codice_fiscale varchar(16) not null unique,
        cognome varchar(100) not null,
        nome varchar(100) not null,
        email varchar(255),
        primary key (id)
    );

    alter table if exists abbonamento_attivita 
       add constraint FK853iwjge5sco7nac3v8pvs72v 
       foreign key (attivita_id) 
       references attivita;

    alter table if exists abbonamento_attivita 
       add constraint FK7slwjgyb7wchv5gnm07g9m6v1 
       foreign key (abbonamento_id) 
       references abbonamento_socio;

    alter table if exists abbonamento_socio 
       add constraint FK22uaw7830fw71duo88vg10i3m 
       foreign key (id_socio) 
       references socio_palestra;

    alter table if exists certificato_medico 
       add constraint FK4qvmdsjo3bhbkpvla58ue89un 
       foreign key (socio_id) 
       references socio_palestra;
