socio.selectByAttivita= select distinct s from Socio s \
inner join s.abbonementos abb \
inner join abb.attivitas att \
where att.description = :attivita

socio.selectByFilter = select s from Socio s \
left join s.abbonementos abb \
left join abb.attivitas att \
where (:id is null or s.id = :id) \
and (cast(:nome as string) is null or s.nome like concat(cast(:nome as string), '%')) \
and (cast(:cognome as string) is null or s.cognome like concat(cast(:cognome as string), '%')) \
and (:attivita is null or att.id = :attivita)